In [1]:
import numpy as np 
my_lst  = [1,2,3,4]
type(my_lst)

list

In [2]:
arr = np.array(my_lst)
type(arr)

numpy.ndarray

In [3]:
# 2D matrix
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.ndim # number of dimentions

2

In [5]:
a.shape # shape of  matrix 

(2, 3)

In [6]:
b = np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [7]:
b.ndim

2

In [8]:
b.shape

(3, 4)

In [9]:
# 3-D Matrix :
c = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
c

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [10]:
c.shape

(2, 2, 2)

In [11]:
c.ndim

3

In [13]:
x = np.zeros(3)

In [14]:
type(x)

numpy.ndarray

In [15]:
x.ndim

1

In [16]:
# generating zeros 
y = np.zeros((3,5))
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
# Identical matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# diagonal
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
# generate random numbers :
# 0 - 1 (range , only +ve )
b = np.random.rand(4)
b

array([0.8035914 , 0.35806398, 0.94876617, 0.56787521])

In [24]:
c = np.random.randn(4)
c

array([ 0.84450918, -1.07322427, -0.1518239 ,  1.41962591])

In [26]:
# arange
v = np.arange(5)
v

array([0, 1, 2, 3, 4])

In [27]:
x = np.arange(10,dtype = 'float64')
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
d = x[:]
d

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
d1 = x[:4]
d1

array([0., 1., 2., 3.])

In [31]:
d2 = x[4:]
d2

array([4., 5., 6., 7., 8., 9.])

In [33]:
print(x)
d3 = x[3:8]
d3

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([3., 4., 5., 6., 7.])

In [34]:
# handling complex nums in numpy 
d = np.array([1+2j , 3+5j])
type(d)

numpy.ndarray

In [35]:
d

array([1.+2.j, 3.+5.j])

In [36]:
print(d.dtype)

complex128


In [37]:
x = 55
type(x)

int